# This file was generated by JuDoc, do not modify it. # hide
# hideall
import Plots
Plots.pyplot()
Plots.plot(title="Plot of x vs. various linear functions", xlabel="x", ylabel="linear function of x")
Plots.plot!(x -> 0, label="0x")
Plots.plot!(x -> x, label="1x")
Plots.plot!(x -> 3x, label="3x")
Plots.savefig(joinpath(@__DIR__, "linearplot.png"))
