# This file was generated by JuDoc, do not modify it. # hide
# hideall
import Plots
Plots.pyplot()
Plots.plot(title="Square function plot", xlabel="x", ylabel="y = x²")
Plots.scatter!(-5:5, -5:5 .^ 2)
Plots.savefig(joinpath(@__DIR__, "squareintegers.png"))
